### PR TITLE
WIP transform entries

### PR DESCRIPTION
**Pull request by matthewmueller**
Right now the entries cannot be transformed, so if I have something like: `.build('file.coffee')`, I wouldn't be able to turn that into `file.js`

I'm not exactly sure the best way to approach this because you have to modify the tree (replace the `file.coffee` file in the tree with `file.js`), but I'm not sure modifying the tree in the `postread` is a great idea. I was considering adding `file.rename(...)` to the tree and changing the `type` and `path`.

I think it's a matter of just re-arranging when the file is added to the tree though (probably should be added after post-read plugin).

This also makes me wonder if the tree should be "read-only" with a lot of these plugins, except the ones that are run serially, so you don't accidentally shoot yourself in the foot. 

This PR also makes the `file.path` the fullpath for the entries which is more consistent with the dependency's `file.path`.

### CODE REVIEW

**Comment by dominicbarnes** [comment]
I think what you are looking for is setting `file.type = 'js';` after the transform from `.coffee` -> `.js` is complete. (similar to how duo operates)

Unless I am missing something, that is. I haven't used it for this case exactly, since I usually just use `.js` even when using ES6.

**Comment by dominicbarnes** [comment]
@matthewmueller I found the place in the wiki where I added that [little tidbit](https://github.com/makojs/core/wiki/Hooks#postread), but it should definitely be made far more prominent.

**Comment by matthewmueller** [comment]
yep, I read that. the problem that in most cases you'd also want to change the pathname when you output the file, so entry is `file.coffee` out is `file.js`.

When you try and change the pathname too, the graph complains because it doesn't recognize `file.js`, it only recognizes `file.coffee`.

**Comment by dominicbarnes** [comment]
Oh, I see what you mean now! The solution here isn't replacing the node in the tree, as it original file is necessary for future `mtime` checking and such.

The right solution here is to make the [output plugin](https://github.com/makojs/output) smart enough to recognize when `file.type` has changed. Does that make sense? Would you be willing to open a PR over there?

**Comment by matthewmueller** [comment]
> The right solution here is to make the output plugin smart enough to recognize when file.type has changed. Does that make sense? Would you be willing to open a PR over there?

ahh yep! good call. i'll work on that.

**Pull request closed without merging**
