### PR TITLE
Update mako-tree

### PR DESCRIPTION
**Pull request by dominicbarnes**
This updates core to use the changes in the latest mako-tree. Changes of note:

 - "entry" is no longer tracked internally in the tree (though we do still track the input entries on the `Build` object)
 - using the new Vinyl-based files (and all the related changes in tree manipulation/traversal)
 - methods like `.analyze()`, `.assemble()` and `.build()` accept vinyl-like file objects (instead of just string paths)
 - the entire event emitter mechanism has been stripped out (I plan on rewriting mako-cli to leverage hooks instead)

(note to self: squash these commits)

cc @darsain @matthewmueller

### CODE REVIEW

**Comment by matthewmueller** [comment]
😍😍😍

**Comment by darsain** [comment]
I have no objections. This is all I wanted :)

Well, maybe yet:
- make all plugins use `file.base` instead of `option.root`
- source maps be passed on camelcased `sourceMap` property so it matches the rest of the Vinyl ecosystem
- use better CSS dependency parser
- some time down the line creating a dead code elimination/tree shaking plugin

and It's golden : Can't think of any other points how to improve mako atm, and it's a small list :smiley:

**Comment by darsain** [comment]
Actually, thinking about `file.base` as a perfect substitute for `option.root`, how about moving all file related plugin options into the `file` object? `sourceRoot` would be the perfect example.

You could still define it in plugin options object, but it would be overridden by `file.optionName`.

**Comment by matthewmueller** [comment]
Yah I'm +1 to just using `file.base`, but I'd also like setting root to be explicit. Right now presets like mako-browser can't set root because `mako.json` or `package.json` can't specify `__dirname`, so I'd need to use the always to pass in root configuration to something like mako-browser.

This becomes more of a problem when you're pushing code around and you have no idea what current working directory your code is being built from.

**Comment by darsain** [comment]
Yeah, nothing against root config to which all entries will default to unless they have `base` property defined.

But, `file.base` defaults to `file.cwd`, which defaults to `process.cwd()`, which should be the expected behavior in your use cases even without need for root config, no?

**Comment by matthewmueller** [comment]
yep i agree that `process.cwd()` should definitely should be the default

**Comment by darsain** [comment]
Oh that's not a proposal. That's how Vinyl works already :)

**Comment by matthewmueller** [comment]
yah, we just need to be able to set `file.base = __dirname` without using calling the programmatic API

**Pull request merged**
